### ISSUE TITLE
RFC - Javascript translation - Forum 15/08/2016

### ISSUE THREAD

**Issue by PXke** [inveniosoftware/invenio-i18n#34]
# Introduction

The [forum of the 15/08/2016](https://indico.cern.ch/event/562775/) was about translation. 

The goal was to see an already implemented solution at [Indico](https://indico.cern.ch/) for client-side translation. 

@pferreir has shown us a really interesting [presentation](https://indico.cern.ch/event/562775/contributions/2273907/attachments/1323429/1985714/indico-i18n.pdf) about how they solved the problem using [JED](https://slexaxton.github.io/Jed/).
# Questions

This presentation has raised several interrogations about the state of translation in Invenio and how we could use [JED](https://slexaxton.github.io/Jed/) in it. 
## Translation of the REST API.

This is a point raised by @nharraud. 

> This is a philosophical question,  do we translate REST API messages
> @jirikuncar 

Do we want to translate the REST API error messages?
It seems to be a necessity in some case but can be really complicated as it can be a lot of different errors. Also some services have perhaps not prepared for it. 

If we decide to translate REST API messages, should we translate them server-side or client side ? 

It also calls for the constitution of guide lines. 
## Angular + JED

We currently don't have experience about using [Angular.js](https://angularjs.org/) and [JED](https://slexaxton.github.io/Jed/) at the same time. It exists and uncertainty about if they will work nicely together. 

We need to create a [POC](https://www.techopedia.com/definition/4066/proof-of-concept-poc). 

@jirikuncar  suggested to create a static example out of Invenio just to test if it can work. 
## Special translations

Some languages are read right-to-left ([RTL](https://en.wikipedia.org/wiki/Right-to-left)).

We need to ensure that we can handle them. 

We also need to be sure we can handle all the languages possible. For this we need to list all the special cases that we could meet. 

Eg. RTL, order of variables in sentences etc ... 
## Realization

Should we create a generic flask module for the translations. Can we contribute with @Indico to create such a module ? 

It would be nice because we could reuse the already done work, and contribute back to flask community.

Some other points need to be clarified.

We would need a list of critical module that should be checked first to see if they implement correctly translation. 

The publishing to Transifex in a nice way is also a question that need be solved.

**Comment by lnielsen** [comment]
Just some further bullets to take into account:

- L10N: date, time, number formatting (and possibly sharing definitions between server/client side).
- Message catalogs: How do we 1) share translations between server/client 2) provide defaults, but allow override them by instances.
- Optimisation/Performance: Ensure we don't send more to the client that really necessary.

In addition to this, we're dependent on already existing message catalogs provided by other flask extensions (e.g. Flask-Admin or WTForms). These don't always play nicely with what we have right now.

**Comment by audub** [comment]
Also, we probably need a way to do translation of emails as well.

**Comment by andrewm89** [comment]
Having spent some time reviewing the options, the best way to proceed with what I have seen is the following:
Package: Angular-gettext (https://angular-gettext.rocketeer.be/)
Benefits:
- Keep .po file to be translated for consistency with Babel
- JS translation file is generated automatically during the JS build step, so only need to maintain one .po file
- No need to change Angular syntax in the jinja templates for the translator to recognise the translatable strings (strings marked with translate attribute)
Disadvantages:
- A slight learning curve due to lack of experience however the online examples are clear
Extra packages required for the build:
- angular-gettext-tools
- angular-gettext-cli
- angular-gettext-loader

Having looked at the JED solution alongside gettext, there seems to be a shallower learning curve for gettext, JED is also quite verbose in its usage.  JED is also no longer developed (except bug fixes) and the developer suggests using a different solution.

**Comment by jirikuncar** [comment]
@andrewm89 have you tried the tools to extract messages from Angular templates? Can we still use Babel to extract `messages-js.pot`?

**Comment by andrewm89** [comment]
@jirikuncar The tools extract the messages from the Angular templates and creates a .po file.  This would then have to be merged with the .po from Babel.  The process can me automated in a script however to provide a single file to a translator.  We have a ticket during this coming sprint to properly test the tools on a single module.

**Comment by lnielsen** [comment]
@andrewm89 Thanks for digging into it. How many extra kilobytes is the angular-gettext dependency adding to your bundles?

**Comment by andrewm89** [comment]
Having tested a simple implementation of the solution mentioned above, it seems to work quite well and is fairly simple to implement.  The following PR is still a WIP however: https://github.com/tind/tind-invenio3/pull/116

**Comment by lnielsen** [comment]
The repo you are referencing is not public ;-)

**Comment by tiborsimko** [comment]
Some considerations on this topic: 

- in Invenio 1.x legacy, we have indeed one PO message catalogue that is composed of Python output message and HTML/WML template output messages.  Such a combined catalogue has clear advantages for the translator, since a message appears there exactly once, wherever it is used.  However, in theory one could also have two catalogues, one for the frontend and one for the backend, and automatise message translation propagations via `msgmerge`.

- in Invenio 3, where we have 100+ repositories, there is an additional complication in that some phrase such as "Yes" and "No" could be used all over in various places.  So the `msgmerge` scripting magic would be required in an inter-repository manner in order to ease the translation job for people.

- What would selecting `angular-gettext` mean for non-Angular JS files?  We still have some around... Adopting Angular-only solution would mean to spread Angular more widely into various Invenio packages, possibly opening the question about going for one single Angular app.  So this is another thing to consider...

**Comment by jirikuncar** [comment]
> `msgmerge` scripting magic would be required in an inter-repository manner in order to ease the translation job for people.

Some parts are already automatized by Transifex (see https://www.transifex.com/inveniosoftware/invenio-1/settings/features/#tm).

**Comment by jirikuncar** [comment]
> https://github.com/tind/tind-invenio3/pull/116

https://github.com/inveniosoftware/invenio-i18n/issues/34#issuecomment-242421376 @andrewm89 can you link to an open-source/public repo?

**Comment by jirikuncar** [comment]
We (me and @andrewm89) are planning to work on language selection that keeps frontend and backend language in sync (probably by using cookies) on Tuesday (2016-10-25 @ 9:30).

--
cc @drjova

**Comment by jirikuncar** [comment]
- [ ] fix `<html lang="...">` - use `current_i18n.locale` instead of `g.ln` (https://github.com/inveniosoftware/invenio-theme/issues/73)
- [ ] create macro generating select box with languages (`<form ...POST>...</form>`)
- [ ] `angularGettextHTMLLangSelector` (WIP name) - `setCurrentLanguage(html.lang)` in `/static` folder (add static configuration to views.py)
- [ ] `bundles.py` can include NpmBundle with dependency on Angular-Gettext

--
cc @andrewm89
